site_name: Arch Notes
site_url: https://clarchnotes.github.io

theme:
  name: material
  palette:
    primary: lime
  features:
    - content.action.edit # 编辑按钮
    - content.action.view # 查看源代码按钮
    - content.code.copy # 支持代码块复制
    - navigation.footer # 上一页和下一页
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中
    - search.suggest
    - search.highlight
    - search.share
  language: "zh"

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - CPU:
      - CPU/index.md
      - "Frontend":
          - "Decoder":
              - CPU/fontend/decoder/ht_write_decoder.md
      - "Backend":
          - "LSU":
              - CPU/Backend/LSU/basics.md
              - "Xiangshan":
                  - CPU/Backend/LSU/xiangshan/index.md
                  - "LSU Microarchitecture": CPU/Backend/LSU/xiangshan/lsu_microarch.md
                  - "LSQ":
                      - CPU/Backend/LSU/xiangshan/lsq/freelist.md
                      - CPU/Backend/LSU/xiangshan/lsq/virtual_load_queue.md
                      - CPU/Backend/LSU/xiangshan/lsq/load_queue.md
                      - CPU/Backend/LSU/xiangshan/lsq/load_queue_raw.md
                      - CPU/Backend/LSU/xiangshan/lsq/load_queue_rar.md
                      - CPU/Backend/LSU/xiangshan/lsq/load_queue_replay.md
              - "MDP":
                  - CPU/Backend/LSU/MDP/papers.md
  - RVV:
      - RVV/index.md
      - "ISA":
          - RVV/ISA/index.md
          - RVV/ISA/reduction.md
          - RVV/ISA/permutation.md
          - RVV/ISA/int_arith.md
